spring:
  profiles:
    active: local

  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.H2Dialect

  datasource:
    platform: local
    url: jdbc:h2:~/syncyoutube;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE

  h2:
    console:
      enabled: true