spring:
  profiles:
    active: local

  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.H2Dialect

  datasource:
    platform: local
    url: jdbc:h2:~/syncyoutube;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE

  h2:
    console:
      enabled: true

server:
  port: 8090 #Https port
  ssl:
    enabled: true
    key-store: /Users/kimdaeyoung/Desktop/kimneutral_keystore.jks # 1번에서 생성한 Key store 경로와 파일명을 적어줍니다.
    key-store-password: 123456  # 1번에서 생성한 Key store의 비밀번호를 적어줍니다.
    key-password: 123456 # 1번에서 생성한 키스토어의 마지막의 키 비밀번호
    key-alias: kimneutral # 키 스토어 별칭
    trust-store: /Users/kimdaeyoung/Desktop/kimneutral_keystore.ts # 2번에서 생성한 Trust-Store 경로
    trust-store-password: 123456 # Trust-Store 비밀번호